### ISSUE TITLE
Navbar in auth page

### ISSUE THREAD

**Issue by khulqu15** [khulqu15/hayago_platform#1]
Create new componentt for auth

![WhatsApp Image 2024-01-21 at 15 29 54](https://github.com/khulqu15/hayago_platform/assets/59632952/8884844f-23ad-4a9e-bbed-94e742447d0d)

**Comment by khulqu15** [comment]
sisipkan screenshot juga.

**Comment by Zienararya** [comment]
### Done
![Screenshot_20240121-200652~2](https://github.com/khulqu15/hayago_platform/assets/90743006/614d4c27-936f-4cef-8ffb-440dd5e48348)

**Comment by Zienararya** [comment]
### update, add close button

![Screenshot_20240121-202029~2](https://github.com/khulqu15/hayago_platform/assets/90743006/35af415b-5d0c-4516-9c5f-c523f083aa28)

**Comment by khulqu15** [comment]
ini di branch main ?

**Comment by Zienararya** [comment]
barusan di push mas

**Comment by khulqu15** [comment]
change the branch when you'll push your code into github
